services:
  localhost:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: banking
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
        
  gremlin-server:
    image: tinkerpop/gremlin-server:latest
    platform: linux/amd64
    container_name: banking_gremlin_server
    restart: unless-stopped
    ports:
      - "${GREMLIN_PORT}:8182"
    volumes:
      - ./gremlin-conf:/opt/gremlin-server/conf
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8182/status" ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s

volumes:
  pgdata:
