services:
  localhost:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: banking
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
        
  gremlin-server:
    image: tinkerpop/gremlin-server:latest
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "8182:8182"

volumes:
  pgdata:
